### PR TITLE
Rerender and new version to get osx-64 gfortran 11 from global pinning.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
I think by accident (or not) this also bumped the MSVC version to 2019.

**Comment by erykoff** [comment]
That’s what’s in the global pinning. Is that a problem?

**Comment by wolfv** [comment]
The PR message at least didn't mention it :)

I don't think it's a "problem", probably good improvement. However, `windows-latest` Github Actions don't work with `vs2019` so they broke for us (we had to go to `windows-2019` instead). I don't know why they kept working with vs2017 though.

**Comment by erykoff** [comment]
Many apologies!  However, I think you can specify `compilers` and a specific windows compiler version and it will work.

**Pull request merged**
